/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DailyNoteComparisonPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_DAILY_COMPARISON = "daily-note-comparison-view";
var DailyNoteComparisonPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Daily Note Comparison Plugin");
    this.registerView(
      VIEW_TYPE_DAILY_COMPARISON,
      (leaf) => new DailyComparisonView(leaf)
    );
    this.addRibbonIcon("calendar-days", "Compare Daily Notes", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-daily-comparison",
      name: "Open Daily Note Comparison",
      callback: () => {
        this.activateView();
      }
    });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_DAILY_COMPARISON);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({
        type: VIEW_TYPE_DAILY_COMPARISON,
        active: true
      }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  onunload() {
    console.log("Unloading Daily Note Comparison Plugin");
  }
};
var DailyComparisonView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
  }
  getViewType() {
    return VIEW_TYPE_DAILY_COMPARISON;
  }
  getDisplayText() {
    return "Daily Note Comparison";
  }
  getIcon() {
    return "calendar-days";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("daily-comparison-view");
    const title = container.createEl("h4", {
      text: "Daily Notes - Same Day Across Years",
      cls: "daily-comparison-title"
    });
    const today = (0, import_obsidian.moment)();
    const month = today.format("MM");
    const day = today.format("DD");
    const yearsContainer = container.createEl("div", {
      cls: "daily-comparison-years"
    });
    const years = [2025, 2024, 2023];
    for (const year of years) {
      await this.renderYearSection(yearsContainer, year, month, day);
    }
    this.addStyles();
  }
  async renderYearSection(container, year, month, day) {
    const yearSection = container.createEl("div", {
      cls: "daily-comparison-year-section"
    });
    const yearHeader = yearSection.createEl("div", {
      cls: "daily-comparison-year-header"
    });
    yearHeader.createEl("h5", { text: `${year}-${month}-${day}` });
    const contentArea = yearSection.createEl("div", {
      cls: "daily-comparison-content"
    });
    const possiblePaths = [
      `${year}-${month}-${day}.md`,
      `Daily Notes/${year}-${month}-${day}.md`,
      `Journal/${year}-${month}-${day}.md`,
      `${year}/${year}-${month}-${day}.md`,
      `${year}/${month}/${year}-${month}-${day}.md`
    ];
    let file = null;
    for (const path of possiblePaths) {
      const f = this.app.vault.getAbstractFileByPath(path);
      if (f instanceof import_obsidian.TFile) {
        file = f;
        break;
      }
    }
    if (file) {
      const content = await this.app.vault.read(file);
      const fileToOpen = file;
      const linkButton = yearHeader.createEl("button", {
        text: "\u{1F4D6} Open",
        cls: "daily-comparison-open-btn"
      });
      linkButton.addEventListener("click", () => {
        this.app.workspace.getLeaf().openFile(fileToOpen);
      });
      const preview = contentArea.createEl("div", {
        cls: "daily-comparison-preview"
      });
      await this.renderMarkdown(content, preview, file.path);
    } else {
      contentArea.createEl("p", {
        text: "No daily note found for this date",
        cls: "daily-comparison-no-note"
      });
    }
  }
  async renderMarkdown(markdown, el, sourcePath) {
    await this.app.markdown.renderer.render(
      markdown,
      el,
      sourcePath,
      this
    );
  }
  addStyles() {
    const style = document.createElement("style");
    style.textContent = `
			.daily-comparison-view {
				padding: 10px;
				height: 100%;
				overflow-y: auto;
			}

			.daily-comparison-title {
				margin-bottom: 15px;
				color: var(--text-normal);
				border-bottom: 2px solid var(--background-modifier-border);
				padding-bottom: 8px;
			}

			.daily-comparison-years {
				display: flex;
				flex-direction: column;
				gap: 15px;
			}

			.daily-comparison-year-section {
				border: 1px solid var(--background-modifier-border);
				border-radius: 8px;
				padding: 10px;
				background: var(--background-secondary);
			}

			.daily-comparison-year-header {
				display: flex;
				justify-content: space-between;
				align-items: center;
				margin-bottom: 10px;
				padding-bottom: 8px;
				border-bottom: 1px solid var(--background-modifier-border);
			}

			.daily-comparison-year-header h5 {
				margin: 0;
				color: var(--text-accent);
				font-weight: 600;
			}

			.daily-comparison-open-btn {
				padding: 4px 12px;
				background: var(--interactive-accent);
				color: var(--text-on-accent);
				border: none;
				border-radius: 4px;
				cursor: pointer;
				font-size: 12px;
			}

			.daily-comparison-open-btn:hover {
				background: var(--interactive-accent-hover);
			}

			.daily-comparison-content {
				max-height: 300px;
				overflow-y: auto;
				padding: 8px;
				background: var(--background-primary);
				border-radius: 4px;
			}

			.daily-comparison-preview {
				font-size: 0.9em;
				line-height: 1.6;
			}

			.daily-comparison-no-note {
				color: var(--text-muted);
				font-style: italic;
				text-align: center;
				padding: 20px;
			}
		`;
    document.head.appendChild(style);
  }
  async onClose() {
  }
};
